insert into authors (id, first_name, last_name) values (1, 'Aldwin', 'Maddison');
insert into authors (id, first_name, last_name) values (2, 'Marlene', 'Claydon');
insert into authors (id, first_name, last_name) values (3, 'Maurits', 'Brende');
insert into authors (id, first_name, last_name) values (4, 'Constantine', 'Garton');
insert into authors (id, first_name, last_name) values (5, 'Kali', 'Barends');
insert into authors (id, first_name, last_name) values (6, 'Courtnay', 'Farleigh');
insert into authors (id, first_name, last_name) values (7, 'Yorke', 'MacDwyer');
insert into authors (id, first_name, last_name) values (8, 'Cristiano', 'Peasey');
insert into authors (id, first_name, last_name) values (9, 'Tod', 'Woolaston');
insert into authors (id, first_name, last_name) values (10, 'Jen', 'Cunney');
insert into authors (id, first_name, last_name) values (11, 'Shalom', 'Rodbourne');
insert into authors (id, first_name, last_name) values (12, 'Collin', 'Spaughton');
insert into authors (id, first_name, last_name) values (13, 'Honoria', 'Matthesius');
insert into authors (id, first_name, last_name) values (14, 'Daron', 'Scarce');
insert into authors (id, first_name, last_name) values (15, 'Khalil', 'Arnull');
insert into authors (id, first_name, last_name) values (16, 'Tisha', 'Dauber');
insert into authors (id, first_name, last_name) values (17, 'Tedd', 'Burles');
insert into authors (id, first_name, last_name) values (18, 'Randie', 'Andreas');
insert into authors (id, first_name, last_name) values (19, 'Karlene', 'Granger');
insert into authors (id, first_name, last_name) values (20, 'Major', 'Mattersley');
insert into authors (id, first_name, last_name) values (21, 'Hatti', 'Skelbeck');

insert into books (id, price, price_old, title, author_id) values (1, 1642, 1843, 'Bitwolf', 1);
insert into books (id, price, price_old, title, author_id) values (2, 707, 1451, 'Tres-Zap', 2);
insert into books (id, price, price_old, title, author_id) values (3, 1590, 2445, 'Daltfresh', 3);
insert into books (id, price, price_old, title, author_id) values (4, 2951, 2425, 'Namfix', 4);
insert into books (id, price, price_old, title, author_id) values (5, 2267, 2139, 'Sonsing', 5);
insert into books (id, price, price_old, title, author_id) values (6, 2403, 1007, 'Bytecard', 6);
insert into books (id, price, price_old, title, author_id) values (7, 2271, 3149, 'Tempsoft', 7);
insert into books (id, price, price_old, title, author_id) values (8, 2855, 3279, 'Holdlamis', 8);
insert into books (id, price, price_old, title, author_id) values (9, 1857, 1329, 'Fix San', 9);
insert into books (id, price, price_old, title, author_id) values (10, 2569, 1961, 'Ventosanzap', 10);
insert into books (id, price, price_old, title, author_id) values (11, 1429, 3820, 'Toughjoyfax', 11);
insert into books (id, price, price_old, title, author_id) values (12, 1204, 1226, 'Sub-Ex', 12);
insert into books (id, price, price_old, title, author_id) values (13, 1838, 2604, 'Bigtax', 13);
insert into books (id, price, price_old, title, author_id) values (14, 661, 2748, 'Rank', 14);
insert into books (id, price, price_old, title, author_id) values (15, 2202, 2667, 'Matsoft', 15);
insert into books (id, price, price_old, title, author_id) values (16, 1666, 1960, 'Konklux', 16);
insert into books (id, price, price_old, title, author_id) values (17, 2855, 1371, 'Konklab', 17);
insert into books (id, price, price_old, title, author_id) values (18, 1409, 2659, 'Fintone', 18);
insert into books (id, price, price_old, title, author_id) values (19, 862, 2119, 'Prodder', 19);
insert into books (id, price, price_old, title, author_id) values (20, 2954, 1399, 'Zontrax', 20);
insert into books (id, price, price_old, title, author_id) values (21, 2307, 3157, 'Lotstring', 21);
